version: '3'

services:
  site:
    build:
      context: site
    image: duderman/mangalik
    restart: unless-stopped
    networks:
      - site-network
  email_sender:
    build:
      context: email_sender
    image: duderman/mangalik-email_sender
    restart: unless-stopped
    networks:
      - site-network
      - email-network
    environment:
      - DEBUG=express:*
      - SMTP_HOST=exim
      - SMTP_PORT=25
      - EMAILS_RECEIVER
      - SMTP_USER
      - SMTP_PASS
  exim:
    build:
      context: exim
    image: duderman/mangalik-exim
    restart: unless-stopped
    networks:
      - email-network
    environment:
      - PRIMARY_HOST=xn--80aaivkedj.xn--p1ai
    volumes:
      - /data:/data
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - site
      - email_sender
    networks:
      - site-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  site-network:
  email-network:
